services:
  - type: web
    name: chatbot-service
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatbot-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
    healthCheckPath: /health
    healthCheckTimeout: 100s

  - type: redis
    name: chatbot-redis
    plan: free
    ipAllowList: []

databases:
  - name: chatbot-db
    plan: free 